export const GTFRI_FIELD_NAMES = {
    1: "protocol",
    2: "imei",
    3: "deviceName",
    8: "reportType",
    9: "ecuErrorCode",
    10: "accuracy",
    11: "speed",
    12: "azimuth",
    13: "altitude",
    14: "longitude",
    15: "latitude",
    16: "utcTime",
    18: "mcc",
    19: "mnc",
    20: "lac",
    21: "cellId",
    22: "csq",
    23: "networkType",
    24: "state",
    25: "powerSupply",
    26: "mainVoltageMv",
    27: "backupVoltageMv",
    28: "backupBatteryPercent",
    29: "errorType",
    30: "alive",
    31: "locked",
    34: "scooterBatteryPercent",
    35: "generatedTime",
    36: "countNumber"
};

export const GTMLS_FIELD_NAMES = {
    1: "protocol",
    2: "imei",
    3: "deviceName",
    7: "lockType",
    8: "lockState",
    9: "generatedTime",
    10: "countNumber",
};

export const GTNCN_FIELD_NAMES = {
    1: "protocol",
    2: "imei",
    3: "deviceName",
    8: "terminationCode",
    9: "ecuErrorCode",
    10: "accuracy",
    11: "speed",
    12: "azimuth",
    13: "altitude",
    14: "longitude",
    15: "latitude",
    16: "utcTime",
    18: "mcc",
    19: "mnc",
    20: "lac",
    21: "cellId",
    22: "csq",
    23: "networkType",
    24: "state",
    25: "powerSupply",
    26: "mainVoltageMv",
    27: "backupVoltageMv",
    28: "backupBatteryPercent",
    29: "errorType",
    30: "alive",
    31: "locked",
    34: "scooterBatteryPercent",
    35: "generatedTime",
    36: "countNumber"
};

export const STANDARD_FIELD_NAMES = {
    1: "protocol",
    2: "imei",
    3: "deviceName",
    4: "vin",
    5: "qrCode",
    10: "accuracy",
    11: "speed",
    12: "azimuth",
    13: "altitude",
    14: "longitude",
    15: "latitude",
    16: "utcTime",
    18: "mcc",
    19: "mnc",
    20: "lac",
    21: "cellId",
    24: "state",
    25: "powerSupply",
    26: "mainVoltageMv",
    27: "backupVoltageMv",
    28: "backupBatteryPercent",
    35: "generatedTime",
    36: "countNumber"
};

export const GTHBD_FIELD_NAMES = {
    1: "protocol",
    2: "imei",
    3: "deviceName",
    4: "BLE", // reserved
    5: "generatedTime",
    6: "countNumber",
};